version: '3.8'
services:
  entitystoreapi:
    image: datawx/ollamapool_server
    environment:
      - ENDPOINT_QUERIES=${ENDPOINT_QUERIES}
      - ENDPOINT_RESULTS=${ENDPOINT_RESULTS}
      - ENDPOINT_NODESTATUS=${ENDPOINT_NODESTATUS}
      - OLLAMA_HOST=${OLLAMA_HOST}
    networks:
      - op_network
networks:
  op_network:
    driver: bridge
